#!/bin/bash

RED='\033[0;31m'
NC='\033[0m'

if ! cp ./scripts/pre-commit ./.git/hooks/pre-commit; then
  echo -e "${RED}Failed to install git hook${NC}"
  exit 1
fi

echo "Checking code formatting"

./gradlew app:ktlintCheck --daemon

STATUS=$?

[ $STATUS -ne 0 ] && exit 1
exit 0
