name: ktlint_ci
on:
  pull_request:
    branches:
      - develop
jobs:
  ktlint:
    name: Check Code Quality
    runs-on: ubuntu-latest
    steps:
      - name: Clone repo
        uses: actions/checkout@master
        with:
          fetch-depth: 1
      - name: ktlint
        uses: ScaCap/action-ktlint@master
        with:
          github_token: ${{ secrets.action_token }}
          level: info
          reporter: github-pr-check
